apiVersion: v1
kind: Service
metadata:
  name: react-nginx-service
  namespace: app-ns
  labels:
    app: react-nginx-app
spec:
  selector:
    app: react-nginx-ui
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      targetPort: 3000
